server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: Upen@1988
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: HotelService
    
    
okta:
  oauth2:
    issuer: https://dev-59401106.okta.com/oauth2/default
    audience: api://default
    
#    
#eureka:
#  instance:
#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  